# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        work_dir:
          - ./
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Build
        run: |
          make build

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ${{ matrix.work_dir }}
          config: .golangci.yml

      - name: Test
        working-directory: ${{ matrix.work_dir }}
        run: |
          go mod tidy 
          go test -v ./...
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        work_dir:
#          - ./
#    steps:
#      - uses: actions/checkout@v3
#      - name: Install Go
#        uses: actions/setup-go@v4
#        with:
#          go-version: 1.20
#
#      - name: Deploy
#        run: |
#          docker login -u samarec1812 --password ${{secrets.DOCKER_TOKEN}}
#          docker build -f build/Dockerfile -t samarec1812/currency-rates:latest .
#          docker push samarec1812/currency-rates:latest
#
#
